name: Evinced Examples CI/CD tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    strategy:
      matrix:
        language-folder:
          - { language: "javascript", folder: "js-wdio-web" }
          - { language: "typescript", folder: "ts-wdio-web" }
          - { language: "javascript", folder: "js-playwright" }
          - { language: "typescript", folder: "ts-playwright" }
          # - { language: "javascript", folder: "js-cypress" }
          # - { language: "typescript", folder: "ts-cypress" }
          - { language: "javascript", folder: "react-unit-tester" }
          - { language: "javascript", folder: "nextjs-react-unit-tester" }
          - { language: "javascript", folder: "js-wdio-mobile" }
          - { language: "javascript", folder: "js-selenium-web" }
          - { language: "javascript", folder: "vitest-react-unit-tester" }

    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          channel: "#workflows"
          message: "Starting tests for folder: ${{ matrix.language-folder.folder }}"
        if: always()

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment for ${{ matrix.language-folder.language }}
        run: |
          if [ "${{ matrix.language-folder.language }}" == "javascript" ] || [ "${{ matrix.language-folder.language }}" == "typescript" ]; then
            echo "Setting up Node.js environment"
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
          elif [ "${{ matrix.language-folder.language }}" == "dotnet" ]; then
            echo "Setting up .NET environment"
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-8.0
          fi
      - name: Configure .npmrc
        run: |
          echo "${{ secrets.EVINCED_NPM_TOKEN }}" > ~/.npmrc

      - name: Install dependencies
        run: |
          cd ${{ matrix.language-folder.folder }}
          if [ "${{ matrix.language-folder.language }}" == "dotnet" ]; then
            dotnet restore
          else
            npm install
          fi

      - name: Install Playwright browsers
        if: contains(matrix.language-folder.folder, 'playwright')
        run: |
          cd ${{ matrix.language-folder.folder }}
          npx playwright install

      - name: Install matching Chromedriver
        if: matrix.language-folder.folder == 'js-selenium-web'
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
          echo "Detected Chrome version: $CHROME_VERSION"
          npm install chromedriver@$CHROME_VERSION

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Evinced Smoke tests
        id: run-tests
        env:
          EVINCED_SERVICE_ID: ${{ secrets.EVINCED_SERVICE_ID }}
          EVINCED_API_KEY: ${{ secrets.EVINCED_API_KEY }}
          SAUCE_USER: ${{ secrets.SAUCE_USER }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: |
          cd ${{ matrix.language-folder.folder }}
          if [ "${{ matrix.language-folder.folder }}" == "js-wdio-mobile" ]; then
            echo "Running WebDriverIO Mobile tests"
            npm run wdio
          elif [ -f "wdio.conf.js" ] || [ -f "wdio.conf.ts" ]; then
            echo "Running WebDriverIO tests"
            npm run wdio
          elif [ -f "playwright.config.js" ] || [ -f "playwright.config.ts" ]; then
            echo "Running Playwright tests"
            npx playwright test
          elif [ "${{ matrix.language-folder.folder }}" == "js-selenium-web" ]; then
            echo "Running Selenium tests"
            npm test
          elif [ "${{ matrix.language-folder.folder }}" == "nextjs-react-unit-tester" ]; then
            echo "Running Nextjs Jest Unit Tester tests"
            npm test
          elif [ "${{ matrix.language-folder.folder }}" == "vitest-react-unit-tester" ]; then
            echo "Running Vitest Unit Tester tests"
            npm test
          else
            echo "Running standard tests"
            npm run test
          fi

      - name: Upload HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language-folder.folder }}-report
          path: |
            ${{ matrix.language-folder.folder }}/**/*.html

      - uses: act10ns/slack@v2
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()

  download-reports:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          path: reports
